monolog:
    channels: ['consumer']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        consumer:
            type: stream
            path: "%kernel.logs_dir%/consumer/consumer.log"
            level: info
            channels: [consumer]
            formatter: json_formatter